name: Deploy to GitHub Pages (Pre-built)

on:
  push:
    branches:
      - release # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build # Path to your pre-built folder
          clean: true
